apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sampleapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sampleapi-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50